// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package db

import (
	"github.com/google/uuid"
)

type Event struct {
	ID    uuid.UUID
	Title string
}

type User struct {
	ID       uuid.UUID
	Username string
	Password string
}
